# Generated by Django 4.2.5 on 2023-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesvazy', '0002_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
